### PR TITLE
Handle recursion of class instances

### PR DESCRIPTION
**Pull request by Whatshiywl**
If value is an instance of a class, transform it to a plain object

### CODE REVIEW

**Comment by satazor** [comment]
Hello @Whatshiywl. Thanks for the PR but this module intentionally stops recursion on non plain JavaScript options. If that’s something that you want, you may fork this package and change that.

**Comment by Whatshiywl** [comment]
Oh I'm sorry, I wasn't aware of that. Might I suggest adding such behavior as a configurable option at least? I could implement it myself and submit another pull request if you're interested.

**Comment by satazor** [comment]
I want to keep this module simple so I don’t want to over complicate it. Still, if you do the module, I will happily include in the readme for users looking for that behavior.

Hope you understand.

**Comment by Whatshiywl** [comment]
Fair enough! I think I'll just clone it and use the modified version for now then.

Cheers!

**Pull request closed without merging**
